# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
  release:   
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - name: Read version-check.json
      id: versioncheck
      uses: pCYSl5EDgo/cat@master
      with:
        path: ./version-check.json
    - name: Read version
      id: version
      run: grep '-latest"' version-check.json | awk '{print $3}'
    - name: Create GitHub Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.version.outputs.text }}
        commitish: master
        name: ${{ steps.version.outputs.text }}
        prerelease: false
        allow_override: false
        gzip: false
        files: |
            ./build/libs/LogisticsBridge-${{ steps.version.outputs.text }}.jar
