# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and release

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for version
      run: grep "latest" version-check.json | grep '[0-9]*\.[0-9]*\.[0-9]*' >> version
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Read version
      id: version
      uses: pCYSl5EDgo/cat@master
      with:
        path: ./version
        trim: true
    - name: Create GitHub Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.version.outputs.text }}
        commitish: master
        name:  ${{ steps.version.outputs.text }}
        prerelease: false
        allow_override: false
        gzip: false
        files: |
            ./build/libs/LogisticsBridge.jar
